### ISSUE TITLE
The script goes into an infinite loop if config.lowerlimitdate is of a month/year older than the current month/year

### ISSUE THREAD

**Issue by CodeMaxx** [shashwatjolly/us-visa-appointment-tool#1]
This is the loop at fault:

<img width="991" alt="image" src="https://user-images.githubusercontent.com/14044709/199623776-782ffbda-81ec-49d3-ab5c-fc5e60ef8f3e.png">

**Comment by shashwatjolly** [comment]
Yeah, I didn't expect that the lower limit date can be older than the current date - but on second thought, it can be problematic if you set the lower limit date to be a future date, and the current date catches up to the lower limit date set earlier.
Should be an easy fix, will do it soon, thanks!

**Comment by CodeMaxx** [comment]
Yep, that's the exact scenario that happened to me.

**Comment by shashwatjolly** [comment]
Fixed with [the latest commit](https://github.com/shashwatjolly/us-visa-appointment-tool/commit/98305ec6eed42c6e3222cff62b7a1c1e9b15bf4b).
