### ISSUE TITLE
group appointment support

### ISSUE THREAD

**Issue by saygeese** [shashwatjolly/us-visa-appointment-tool#2]
It would be great if the group appointment (multiple applicants in one appointment) could be supported.

**Comment by sarathbp** [comment]
Is it supporting Group aaplication?

**Comment by sarathbp** [comment]
The tool will search for appointments on/after:  2023-02-02T04:00:00.000Z
Error:  ReferenceError: max is not defined
    at main (file:///C:/Users/sarat/OneDrive/Documents/GitHub/us-visa-appointment-tool/index.js:51:9)

**Comment by shashwatjolly** [comment]
I am not sure if the script would support group applications. I had created the script when I was booking my own appointment (which wasn't a group appointment), and I no longer have a way of testing it out :)

For the "ReferenceError: max is not defined" issue, I pushed a fix. Please pull the latest changes and try again.
