### ISSUE TITLE
error running the script

### ISSUE THREAD

**Issue by dhruvgupta1730** [shashwatjolly/us-visa-appointment-tool#4]
Hi, can you please help, I am getting this error. @shashwatjolly @jahnvi12 

Current appointment date found:  2024-07-31T07:00:00.000Z
The tool will search for appointments on/after:  2023-04-10T07:00:00.000Z
Error:  TypeError: lowerLimitDate.getMonth is not a function
    at main (file:///Users/bodmas/dev/us-visa-appointment-tool-main/index.js:54:66)

**Comment by dhruvgupta1730** [comment]
can you please help ?

**Comment by rupendersingh** [comment]
Replace the line with 
lowerLimitDate = new Date(Math.max(lowerLimitDate, currentDate));

**Comment by dhruvgupta1730** [comment]
@rupendersingh in index.js ?

**Comment by rupendersingh** [comment]
You need to replace below line in Index.js
lowerLimitDate = Math.max(lowerLimitDate, currentDate);
 with 
**lowerLimitDate = new Date(Math.max(lowerLimitDate, currentDate));**

**Comment by shashwatjolly** [comment]
Fixed, sorry for the delay!
