### ISSUE TITLE
Error:  TypeError: lowerLimitDate.getMonth is not a function     at main (file:///C:/US%20Visa%20Tool/us-visa-appointment-tool-main/index.js:54:66)

### ISSUE THREAD

**Issue by mlkpuri** [shashwatjolly/us-visa-appointment-tool#7]
Error:  TypeError: lowerLimitDate.getMonth is not a function
    at main (file:///C:/US%20Visa%20Tool/us-visa-appointment-tool-main/index.js:54:66)

**Comment by shashwatjolly** [comment]
Fixed, sorry for the delay!
